// Script feito por Brock Investimentos 
// @Youtube -  Brock Investimentos - https://www.youtube.com/channel/UCXzzaYaHVzoFVDNs8RPKR5Q

// VIDEO EXPLICANDO

//@version=4

study("Ciclo Azul e Rosa - (script by Brock Investimentos)", overlay=true)

minHour = input(defval=0, title="Começo dos trade (hora)", minval=0, maxval=23)
maxHour = input(defval=23, title="Fechar todas as operações (hora)", minval=0, maxval=23)
tradingWindow = hour >= minHour and hour <= maxHour

pinkCycleEnabled = input(title="Ciclo Rosa", type=input.bool, defval=true)
blueCycleEnabled = input(title="Ciclo Azul", type=input.bool, defval=true)
greenCycleEnabled = input(title="Ciclo Verde", type=input.bool, defval=true)
orangeCycleEnabled = input(title="Ciclo Laranja", type=input.bool, defval=true)

isGreenCandle(index) => close[index] > open[index]
isRedCandle(index) => close[index] < open[index]

blueCycleType1 = isRedCandle(3)   and isGreenCandle(2) and isGreenCandle(1) and isGreenCandle(0)
blueCycleType2 = isGreenCandle(3) and isRedCandle(2)   and isRedCandle(1)   and isRedCandle(0)
blueCycle = blueCycleType1 or blueCycleType2

pinkCycleType1 = isRedCandle(3)   and isGreenCandle(2) and isGreenCandle(1) and isRedCandle(0)
pinkCycleType2 = isGreenCandle(3) and isRedCandle(2)   and isRedCandle(1)   and isGreenCandle(0)
pinkCycle = pinkCycleType1 or pinkCycleType2

greenCycleType1 = isGreenCandle(4) and isGreenCandle(3) and isRedCandle(2)   and isGreenCandle(1) and isRedCandle(0)
greenCycleType2 = isRedCandle(4)   and isRedCandle(3)   and isGreenCandle(2) and isRedCandle(1)   and isGreenCandle(0)
greenCycle = greenCycleType1 or greenCycleType2

orangeCycleType1 = isRedCandle(4)   and isRedCandle(3)   and isGreenCandle(2) and isRedCandle(1)   and isRedCandle(0)
orangeCycleType2 = isGreenCandle(4) and isGreenCandle(3) and isRedCandle(2)   and isGreenCandle(1) and isGreenCandle(0)
orangeCycle = orangeCycleType1 or orangeCycleType2

bgcolor(blueCycleEnabled and blueCycle and tradingWindow? color.blue : na, 60)
bgcolor(pinkCycleEnabled and pinkCycle and tradingWindow? color.fuchsia : na, 60)
bgcolor(greenCycleEnabled and greenCycle and tradingWindow? color.green : na, 60)
bgcolor(orangeCycleEnabled and orangeCycle and tradingWindow? color.orange : na, 60)
