// Script feito por Brochj
// © brochj

// VIDEO EXPLICANDO - https://www.youtube.com/watch?v=HcXXKhEjnJM&ab_channel=Trade1000Grau

//@version=4

study("OB - MART5 2.0 - Junior Oliveira (script by Brock)", overlay=true)
qtdMartigales = input(title="qtd de Martigales", defval="0", options=["0", "1", "2", "3", "4", "5"])

mg1 = false
mg2 = false
mg3 = false
mg4 = false
mg5 = false

if qtdMartigales == "0"
    mg1 := false
    mg2 := false
    mg3 := false
    mg4 := false
    mg5 := false
else if qtdMartigales == "1"
    mg1 := true
    mg2 := false
    mg3 := false
    mg4 := false
    mg5 := false
else if qtdMartigales == "2"
    mg1 := true
    mg2 := true
    mg3 := false
    mg4 := false
    mg5 := false
else if qtdMartigales == "3"
    mg1 := true
    mg2 := true
    mg3 := true
    mg4 := false
    mg5 := false
else if qtdMartigales == "4"
    mg1 := true
    mg2 := true
    mg3 := true
    mg4 := true
    mg5 := false
else if qtdMartigales == "5"
    mg1 := true
    mg2 := true
    mg3 := true
    mg4 := true
    mg5 := true

minHour = input(defval=0, title="Começo dos trade (hora)", minval=0, maxval=23)
maxHour = input(defval=23, title="Fechar todas as operações (hora)", minval=0, maxval=23)
tradingWindow = hour >= minHour and hour <= maxHour

isGreenCandle(index) => close[index] > open[index]
isRedCandle(index) => close[index] < open[index]
isDoji(index) => close[index] == open[index]

// SHORT
shortEntry = (isGreenCandle(4) or isDoji(4)) and isRedCandle(3) and isRedCandle(2) and isRedCandle(1) 
shortEntryTake = shortEntry and isRedCandle(0) 
shortEntryStop = shortEntry and isGreenCandle(0) and not mg1 and not mg2 and not mg3 and not mg4
bgcolor(shortEntryTake and tradingWindow? color.green : na, 5)
bgcolor(shortEntryStop and tradingWindow? color.red : na,5)

// martigale 1
short_martin1 = (isGreenCandle(5) or isDoji(5)) and isRedCandle(4) and isRedCandle(3) and isRedCandle(2) and isGreenCandle(1)
short_martin1Take = short_martin1 and isRedCandle(0) and mg1 
short_martin1Stop = short_martin1 and isGreenCandle(0) and mg1 and not mg2 and not mg3 and not mg4
bgcolor(short_martin1Take and tradingWindow? color.green : na, 15)
bgcolor(short_martin1Stop and tradingWindow? color.red : na, 15)
plotchar(short_martin1Take and tradingWindow, char="1", size=size.small, color=color.black)

// martigale 2
short_martin2 = (isGreenCandle(6) or isDoji(6)) and isRedCandle(5) and isRedCandle(4) and isRedCandle(3) and isGreenCandle(2) and isGreenCandle(1)
short_martin2Take = short_martin2 and isRedCandle(0) and mg1 and mg2
short_martin2Stop = short_martin2 and isGreenCandle(0) and mg1 and mg2 and not mg3 and not mg4
bgcolor(short_martin2Take and tradingWindow? color.green : na, 5)
bgcolor(short_martin2Stop and tradingWindow? color.red : na,5)
plotchar(short_martin2Take and tradingWindow, char="2", size=size.small, color=color.black)

// martigale 3
short_martin3 =  (isGreenCandle(7) or isDoji(7)) and isRedCandle(6) and isRedCandle(5) and isRedCandle(4) and isGreenCandle(3) and isGreenCandle(2) and isGreenCandle(1)
short_martin3Take = short_martin3 and isRedCandle(0) and mg1 and mg2 and mg3
short_martin3Stop = short_martin3 and isGreenCandle(0) and mg1 and mg2 and mg3 and not mg4
bgcolor(short_martin3Take and tradingWindow? color.green : na, 5)
bgcolor(short_martin3Stop and tradingWindow? color.red : na,5)
plotchar(short_martin3Take and tradingWindow, char="3", size=size.small, location=location.belowbar, color=color.purple)

// martigale 4
short_martin4 = (isGreenCandle(8) or isDoji(8)) and isRedCandle(7) and isRedCandle(6) and isRedCandle(5) and isGreenCandle(4) and isGreenCandle(3) and isGreenCandle(2) and isGreenCandle(1)
short_martin4Take = short_martin4 and isRedCandle(0) and mg1 and mg2 and mg3 and mg4
short_martin4Stop = short_martin4 and isGreenCandle(0) and mg1 and mg2 and mg3 and mg4 and not mg5
bgcolor(short_martin4Take and tradingWindow? color.green : na, 5)
bgcolor(short_martin4Stop and tradingWindow? color.red : na,5)
plotchar(short_martin4Take and tradingWindow, char="4", size=size.small, location=location.belowbar, color=color.purple)

// martigale 5
short_martin5 = (isGreenCandle(9) or isDoji(9)) and isRedCandle(8) and isRedCandle(7) and isRedCandle(6) and isGreenCandle(5) and isGreenCandle(4) and isGreenCandle(3) and isGreenCandle(2) and isGreenCandle(1)
short_martin5Take = short_martin5 and isRedCandle(0) and mg1 and mg2 and mg3 and mg4 and mg5
short_martin5Stop = short_martin5 and isGreenCandle(0) and mg1 and mg2 and mg3 and mg4 and mg5
bgcolor(short_martin5Take and tradingWindow? color.green : na, 5)
bgcolor(short_martin5Stop and tradingWindow? color.red : na,5)
plotchar(short_martin5Take and tradingWindow, char="5", size=size.small, location=location.belowbar, color=color.red)


// LONG ########################################
longEntry = (isRedCandle(4) or isDoji(4)) and isGreenCandle(3) and isGreenCandle(2) and isGreenCandle(1) 
longEntryTake = longEntry and isGreenCandle(0) 
longEntryStop = longEntry and isRedCandle(0) and not mg1 and not mg2 and not mg3 and not mg4
bgcolor(longEntryTake and tradingWindow? color.green : na, 5)
bgcolor(longEntryStop and tradingWindow? color.red : na,5)

// martigale 1
martin1 = (isRedCandle(5) or isDoji(5)) and isGreenCandle(4) and isGreenCandle(3) and isGreenCandle(2) and isRedCandle(1)
martin1Take = martin1 and isGreenCandle(0) and mg1 
martin1Stop = martin1 and isRedCandle(0) and mg1 and not mg2 and not mg3 and not mg4
bgcolor(martin1Take and tradingWindow? color.green : na, 15)
bgcolor(martin1Stop and tradingWindow? color.red : na, 15)
plotchar(martin1Take and tradingWindow, char="1", size=size.small, color=color.black)

// martigale 2
martin2 = (isRedCandle(6) or isDoji(6)) and isGreenCandle(5) and isGreenCandle(4) and isGreenCandle(3) and isRedCandle(2) and isRedCandle(1)
martin2Take = martin2 and isGreenCandle(0) and mg1 and mg2
martin2Stop = martin2 and isRedCandle(0) and mg1 and mg2 and not mg3 and not mg4
bgcolor(martin2Take and tradingWindow? color.green : na, 5)
bgcolor(martin2Stop and tradingWindow? color.red : na,5)
plotchar(martin2Take and tradingWindow, char="2", size=size.small, color=color.black)

// martigale 3
martin3 =  (isRedCandle(7) or isDoji(7)) and isGreenCandle(6) and isGreenCandle(5) and isGreenCandle(4) and isRedCandle(3) and isRedCandle(2) and isRedCandle(1)
martin3Take = martin3 and isGreenCandle(0) and mg1 and mg2 and mg3
martin3Stop = martin3 and isRedCandle(0) and mg1 and mg2 and mg3 and not mg4
bgcolor(martin3Take and tradingWindow? color.green : na, 5)
bgcolor(martin3Stop and tradingWindow? color.red : na,5)
plotchar(martin3Take and tradingWindow, char="3", size=size.small, location=location.belowbar, color=color.purple)

// martigale 4
martin4 = (isRedCandle(8) or isDoji(8)) and isGreenCandle(7) and isGreenCandle(6) and isGreenCandle(5) and isRedCandle(4) and isRedCandle(3) and isRedCandle(2) and isRedCandle(1)
martin4Take = martin4 and isGreenCandle(0) and mg1 and mg2 and mg3 and mg4
martin4Stop = martin4 and isRedCandle(0) and mg1 and mg2 and mg3 and mg4 and not mg5
bgcolor(martin4Take and tradingWindow? color.green : na, 5)
bgcolor(martin4Stop and tradingWindow? color.red : na,5)
plotchar(martin4Take and tradingWindow, char="4", size=size.small, location=location.belowbar, color=color.purple)

// martigale 5
martin5 = (isRedCandle(9) or isDoji(9)) and isGreenCandle(8) and isGreenCandle(7) and isGreenCandle(6) and isRedCandle(5) and isRedCandle(4) and isRedCandle(3) and isRedCandle(2) and isRedCandle(1)
martin5Take = martin5 and isGreenCandle(0) and mg1 and mg2 and mg3 and mg4 and mg5
martin5Stop = martin5 and isRedCandle(0) and mg1 and mg2 and mg3 and mg4 and mg5
bgcolor(martin5Take and tradingWindow? color.green : na, 5)
bgcolor(martin5Stop and tradingWindow? color.red : na,5)
plotchar(martin5Take and tradingWindow, char="5", size=size.small, location=location.belowbar, color=color.red)
